// Run button: the tasks a project offers (package.json scripts, SPFx, Makefile and justfile targets, Cargo,
// Go, Python, .NET, Gradle, Maven, CMake, Deno, Composer, Docker Compose), and spotting the URL a dev
// server prints so it can open in the built-in browser. Looks at the project's top folder only.
const fs = require('fs');
const path = require('path');

const read = (fsx, p) => { try { return fsx.readFileSync(p, 'utf8'); } catch { return null; } };
const json = (fsx, p) => { try { return JSON.parse(read(fsx, p)); } catch { return null; } };

function nodeRunner(names) {
  if (names.has('pnpm-lock.yaml')) return 'pnpm';
  if (names.has('yarn.lock')) return 'yarn';
  if (names.has('bun.lockb') || names.has('bun.lock')) return 'bun';
  return 'npm';
}

// Makefile targets, skipping special (.PHONY), pattern (%) and variable (:=) lines.
function makeTargets(text) {
  const out = [];
  for (const m of String(text || '').matchAll(/^([A-Za-z0-9][\w.-]*)\s*:(?![:=])/gm)) if (!out.includes(m[1])) out.push(m[1]);
  return out;
}

// justfile recipes: `name args: deps` at the start of a line, not settings, aliases or assignments.
function justRecipes(text) {
  const out = [];
  for (const m of String(text || '').matchAll(/^@?([A-Za-z_][\w-]*)(?:\s+[^:=\n]*)?:(?!=)/gm)) {
    if (!['set', 'alias', 'export', 'import', 'mod'].includes(m[1]) && !out.includes(m[1])) out.push(m[1]);
  }
  return out;
}

// Menu names of the task groups (one dropdown each) and the order of sections inside one.
const GROUP_LABELS = {
  npm: 'npm', pnpm: 'pnpm', yarn: 'Yarn', bun: 'Bun', spfx: 'SPFx', dotnet: 'C# / .NET', python: 'Python',
  deno: 'Deno', make: 'make', just: 'just', cargo: 'Cargo', go: 'Go', gradle: 'Gradle', maven: 'Maven',
  cmake: 'CMake', composer: 'Composer', docker: 'Docker'
};
const SECTIONS = ['run', 'test', 'package', 'setup', 'scripts'];
const SECTION_LABELS = { run: 'Run', test: 'Test', package: 'Package', setup: 'Setup', scripts: 'Scripts' };

// package.json script names -> menu section.
function scriptSection(name) {
  if (/^(start|dev|serve|watch|preview)(\W|$)/i.test(name)) return 'run';
  if (/^(test|e2e|lint|typecheck|type-check|check|coverage)(\W|$)/i.test(name)) return 'test';
  if (/^(build|pack|package|dist|bundle|release|publish|ship|deploy)(\W|$)/i.test(name)) return 'package';
  if (/^(clean|setup|prepare|bootstrap|format|fmt)(\W|$)/i.test(name)) return 'setup';
  return 'scripts';
}

// Commands run one after another, stopping at the first failure, in the tab's shell.
// Windows PowerShell 5.1 has no &&.
// Nested in PowerShell: after an `if` that skipped its block, $? is true again, so a flat list would go on.
const chain = (cmds, ps) => (ps ? cmds.reduceRight((rest, c) => (rest ? `${c}; if ($?) { ${rest} }` : c), '') : cmds.join(' && '));

// SharePoint Framework: generated by @microsoft/generator-sharepoint, or has a package-solution config.
function isSpfx(fsx, root, names, pkg) {
  if (names.has('config') && read(fsx, path.join(root, 'config', 'package-solution.json')) !== null) return true;
  const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
  return Object.keys(deps).some((d) => d.startsWith('@microsoft/sp-')) || /generator-sharepoint/.test(read(fsx, path.join(root, '.yo-rc.json')) || '');
}

// Projects a solution file lists: [{ name, file }] with forward slashes.
function slnProjects(text) {
  const out = [];
  for (const m of String(text || '').matchAll(/^Project\("[^"]*"\)\s*=\s*"([^"]+)",\s*"([^"]+\.(?:cs|fs|vb)proj)"/gm)) {
    out.push({ name: m[1], file: m[2].replace(/\\/g, '/') });
  }
  return out;
}

// [{ id, label, command, group, section, first? }] for the folder. group is the menu dropdown, section the
// part of it (run, test, package, setup, scripts). first: shown at the top of its dropdown (install needed).
// ps: the tab shell is PowerShell, which chains commands differently.
function detectTasks(root, { fsx = fs, isWin = process.platform === 'win32', ps = isWin } = {}) {
  let names;
  try { names = new Set(fsx.readdirSync(root)); } catch { return []; }
  const has = (n) => names.has(n);
  const tasks = [];
  const add = (group, label, command, section = 'scripts', extra = {}) => {
    if (!tasks.some((t) => t.group === group && t.command === command)) tasks.push({ id: `${group}:${label}`, group, label, command, section, ...extra });
  };

  if (has('package.json')) {
    const pkg = json(fsx, path.join(root, 'package.json')) || {};
    const runner = nodeRunner(names);
    const scripts = Object.keys(pkg.scripts || {});
    const run = (name) => (runner === 'npm' ? (name === 'start' || name === 'test' ? `npm ${name}` : `npm run ${name}`) : `${runner} ${name === 'install' ? 'run install' : name}`);
    if (!has('node_modules')) add(runner, 'install', `${runner} install`, 'setup', { first: true });
    for (const name of scripts) add(runner, name, run(name), scriptSection(name));
    if (has('node_modules')) add(runner, 'install', `${runner} install`, 'setup');
    if (runner === 'npm' && has('package-lock.json')) add(runner, 'clean install (ci)', 'npm ci', 'setup');
    add(runner, 'outdated packages', `${runner} outdated`, 'setup');
    if (runner === 'npm' || runner === 'pnpm') add(runner, 'security audit', `${runner} audit`, 'setup');
    add(runner, 'pack (.tgz)', runner === 'bun' ? 'bun pm pack' : `${runner} pack`, 'package');

    if (isSpfx(fsx, root, names, pkg)) {
      if (has('gulpfile.js')) {
        add('spfx', 'serve', 'npx gulp serve', 'run');
        add('spfx', 'serve (no browser)', 'npx gulp serve --nobrowser', 'run');
        add('spfx', 'test', 'npx gulp test', 'test');
        add('spfx', 'bundle + package-solution (ship)', chain(['npx gulp bundle --ship', 'npx gulp package-solution --ship'], ps), 'package');
        add('spfx', 'bundle (debug)', 'npx gulp bundle', 'package');
        add('spfx', 'trust dev certificate', 'npx gulp trust-dev-cert', 'setup');
        add('spfx', 'clean', 'npx gulp clean', 'setup');
      } else {
        // SPFx 1.22 and later build with Heft.
        add('spfx', 'start', 'npx heft start --clean', 'run');
        add('spfx', 'test', 'npx heft test', 'test');
        add('spfx', 'build + package-solution (production)', chain(['npx heft test --clean --production', 'npx heft package-solution --production'], ps), 'package');
        add('spfx', 'trust dev certificate', 'npx heft trust-dev-cert', 'setup');
        add('spfx', 'clean', 'npx heft clean', 'setup');
      }
    }
  }
  for (const f of ['deno.json', 'deno.jsonc']) {
    if (!has(f)) continue;
    const cfg = json(fsx, path.join(root, f)) || {};
    for (const name of Object.keys(cfg.tasks || {})) add('deno', name, `deno task ${name}`, scriptSection(name));
  }
  const makefile = ['Makefile', 'makefile', 'GNUmakefile'].find(has);
  if (makefile) for (const t of makeTargets(read(fsx, path.join(root, makefile))).slice(0, 25)) add('make', t, `make ${t}`, scriptSection(t));
  const justfile = ['justfile', 'Justfile', '.justfile'].find(has);
  if (justfile) for (const r of justRecipes(read(fsx, path.join(root, justfile))).slice(0, 25)) add('just', r, `just ${r}`, scriptSection(r));
  if (has('Cargo.toml')) {
    add('cargo', 'run', 'cargo run', 'run');
    add('cargo', 'test', 'cargo test', 'test');
    add('cargo', 'clippy', 'cargo clippy', 'test');
    add('cargo', 'build', 'cargo build', 'package');
    add('cargo', 'build (release)', 'cargo build --release', 'package');
  }
  if (has('go.mod')) {
    add('go', 'run', 'go run .', 'run');
    add('go', 'test', 'go test ./...', 'test');
    add('go', 'vet', 'go vet ./...', 'test');
    add('go', 'build', 'go build ./...', 'package');
  }
  if (has('pyproject.toml') || has('requirements.txt') || has('setup.py')) {
    const uv = has('uv.lock');
    const venv = has('.venv') ? (isWin ? '.venv\\Scripts\\python.exe' : '.venv/bin/python') : null;
    const py = uv ? 'uv run python' : venv || (isWin ? 'python' : 'python3');
    const pyproject = read(fsx, path.join(root, 'pyproject.toml')) || '';
    for (const f of ['main.py', 'app.py']) if (has(f)) add('python', f, `${py} ${f}`, 'run');
    if (has('manage.py')) add('python', 'runserver', `${py} manage.py runserver`, 'run');
    if (has('tests') || has('test') || /pytest/.test(pyproject)) add('python', 'pytest', uv ? 'uv run pytest' : `${py} -m pytest`, 'test');
    else add('python', 'unittest', `${py} -m unittest`, 'test');
    if (/ruff/.test(pyproject)) add('python', 'ruff check', uv ? 'uv run ruff check .' : `${py} -m ruff check .`, 'test');
    if (has('pyproject.toml') || has('setup.py')) add('python', 'build (sdist + wheel)', uv ? 'uv build' : `${py} -m build`, 'package');
    if (uv) add('python', 'sync', 'uv sync', 'setup');
    else {
      if (!venv) add('python', 'create .venv', `${isWin ? 'python' : 'python3'} -m venv .venv`, 'setup');
      if (has('requirements.txt')) add('python', 'install requirements', `${py} -m pip install -r requirements.txt`, 'setup');
      if (has('pyproject.toml') || has('setup.py')) add('python', 'install (editable)', `${py} -m pip install -e .`, 'setup');
    }
  }
  const dotnetFiles = [...names].filter((n) => /\.(csproj|fsproj|vbproj)$/i.test(n));
  const sln = [...names].find((n) => /\.slnx?$/i.test(n));
  if (dotnetFiles.length || sln) {
    // A solution without a project at the top: run each app project in it.
    const apps = dotnetFiles.length ? [] : slnProjects(read(fsx, path.join(root, sln))).filter((p) => !/test/i.test(p.name)).slice(0, 8);
    if (apps.length) {
      for (const p of apps) add('dotnet', `run ${p.name}`, `dotnet run --project "${p.file}"`, 'run');
    } else {
      add('dotnet', 'run', 'dotnet run', 'run');
      add('dotnet', 'watch', 'dotnet watch run', 'run');
    }
    add('dotnet', 'test', 'dotnet test', 'test');
    add('dotnet', 'build', 'dotnet build', 'package');
    add('dotnet', 'build (Release)', 'dotnet build -c Release', 'package');
    add('dotnet', 'publish (Release)', 'dotnet publish -c Release', 'package');
    add('dotnet', 'pack NuGet (Release)', 'dotnet pack -c Release', 'package');
    add('dotnet', 'restore', 'dotnet restore', 'setup');
    add('dotnet', 'clean', 'dotnet clean', 'setup');
    add('dotnet', 'format', 'dotnet format', 'setup');
  }
  if (has('gradlew') || has('gradlew.bat')) {
    const g = isWin ? '.\\gradlew.bat' : './gradlew';
    add('gradle', 'run', `${g} run`, 'run');
    add('gradle', 'test', `${g} test`, 'test');
    add('gradle', 'build', `${g} build`, 'package');
  }
  if (has('pom.xml')) {
    add('maven', 'test', 'mvn test', 'test');
    add('maven', 'package', 'mvn package', 'package');
  }
  if (has('CMakeLists.txt')) {
    add('cmake', 'build', 'cmake --build build', 'package');
    add('cmake', 'configure', 'cmake -S . -B build', 'setup');
  }
  if (has('composer.json')) {
    const c = json(fsx, path.join(root, 'composer.json')) || {};
    for (const name of Object.keys(c.scripts || {})) add('composer', name, `composer run ${name}`, scriptSection(name));
  }
  const compose = ['compose.yaml', 'compose.yml', 'docker-compose.yml', 'docker-compose.yaml'].find(has);
  if (compose) {
    add('docker', 'compose up', 'docker compose up', 'run');
    add('docker', 'compose down', 'docker compose down', 'setup');
  }
  return tasks;
}

const ANSI = /\x1b\[[0-9;?]*[ -/]*[@-~]|\x1b\][^\x07\x1b]*(\x07|\x1b\\)/g;

// The first local URL a dev server prints ("Local: http://localhost:5173/", "listening on 127.0.0.1:3000").
function detectServerUrl(text) {
  const s = String(text || '').replace(ANSI, '');
  const m = /\bhttps?:\/\/(localhost|127\.0\.0\.1|0\.0\.0\.0|\[::1?\])(:\d{2,5})?(\/[^\s'"<>)]*)?/i.exec(s);
  if (m) return m[0].replace('0.0.0.0', 'localhost').replace(/[.,;]+$/, '');
  const bare = /\b(?:listening|running|started|serving|available)\b[^\n]*?\b(?:on|at)\s+(?:port\s+)?(localhost|127\.0\.0\.1|0\.0\.0\.0)?:?(\d{2,5})\b/i.exec(s);
  return bare ? `http://localhost:${bare[2]}` : null;
}

// How an extra terminal runs a command and stays open afterwards (or runs the shell alone).
function auxLaunch({ shell, isWin, command }) {
  const sh = shell || (isWin ? 'powershell.exe' : '/bin/bash');
  const ps = /(^|[\\/])(powershell|pwsh)(\.exe)?$/i.test(sh);
  if (isWin) {
    if (ps) return { file: sh, args: command ? ['-NoLogo', '-NoExit', '-Command', command] : ['-NoLogo'] };
    return { file: sh, args: command ? ['/k', command] : [] }; // cmd.exe
  }
  return { file: sh, args: command ? ['-lc', `${command}; exec ${JSON.stringify(sh)}`] : ['-l'] };
}

module.exports = { detectTasks, scriptSection, slnProjects, chain, GROUP_LABELS, SECTIONS, SECTION_LABELS, makeTargets, justRecipes, detectServerUrl, auxLaunch, nodeRunner };
